### ISSUE TITLE
Traceback

### ISSUE THREAD

**Issue by wesleyadams001** [Subterfuge-Framework/Subterfuge#11]
I am running kali linux rolling distribution and attempted to install subterfuge got this error:
 Traceback (most recent call last):
  File "/bin/subterfuge", line 25, in <module>
    from main.models import *
  File "/usr/share/subterfuge/main/models.py", line 3, in <module>
    class credentials(models.Model):
  File "/usr/lib/python2.7/dist-packages/django/db/models/base.py", line 94, in **new**
    app_config = apps.get_containing_app_config(module)
  File "/usr/lib/python2.7/dist-packages/django/apps/registry.py", line 239, in get_containing_app_config
    self.check_apps_ready()
  File "/usr/lib/python2.7/dist-packages/django/apps/registry.py", line 124, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.

**Comment by dgramop** [comment]
I don't know... something wrong with django is seems.

On Sat, Feb 27, 2016 at 1:31 PM, wesleyadams001 notifications@github.com
wrote:

> I am running kali linux rolling distribution and attempted to install
> subterfuge got this error:
> Traceback (most recent call last):
> File "/bin/subterfuge", line 25, in
> from main.models import *
> File "/usr/share/subterfuge/main/models.py", line 3, in
> class credentials(models.Model):
> File "/usr/lib/python2.7/dist-packages/django/db/models/base.py", line 94,
> in _new_
> app_config = apps.get_containing_app_config(module)
> File "/usr/lib/python2.7/dist-packages/django/apps/registry.py", line 239,
> in get_containing_app_config
> self.check_apps_ready()
> File "/usr/lib/python2.7/dist-packages/django/apps/registry.py", line 124,
> in check_apps_ready
> raise AppRegistryNotReady("Apps aren't loaded yet.")
> django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Subterfuge-Framework/Subterfuge/issues/11.

## 

Regards,

## Dhruv Gramopadhye

Controll Freak Operator and Everything
dGRAMOP Development
Penetration Testing | Animation and Rendering | Web Development | Mobile

## App Development | Embedded Electronics | and Misc Java Development.

http://socnet.16mb.com - My most recent and best project - still buggy,
still work in progress. Feel free to create an account
http://dgramop.co - An index page of my projects
http://m.freeplay.url.ph - A neat looking version of the latter link
http://freeplay.url.ph - An index page of random experiments.
http://ppn.hol.es - A currency system that is online that I use to "bribe"
other children. Over 1.5 years old, I already can name a bunch of security
flaws. Try ../ attack when creating an account.
http://m.ppn.hol.es - An even more neat looking version of the above,
scrolling only works on mobile browsers unless you really zoom in. The junk
text is there to enable scrolling.

**Comment by 0sm0s1z** [comment]
Looks like the Kali folks pushed a Django version update to the repos. Short term fix would be to manually install an older version of Django.

I'll take a look and push an update soon this seems to be a problem that's effecting everyone universally at the moment.

**Comment by 0sm0s1z** [comment]
Issue resolved by: 6c35097

Thanks for all the bug reports guys!
