### ISSUE TITLE
Subterfuge not installing / Django errors (Kali 2.0 Sana)

### ISSUE THREAD

**Issue by ghost** [Subterfuge-Framework/Subterfuge#3]
When i run the setup script i get the following: 

root@kali:~/py/Subterfuge-master# python setup.py
Reading package lists... Done
Building dependency tree  
Reading state information... Done
python-scapy is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree  
Reading state information... Done
python-twisted is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree  
Reading state information... Done
python-django is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree  
Reading state information... Done
arptables is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree  
Reading state information... Done
Note, selecting 'udhcpd' instead of 'dhcpd'
udhcpd is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
rm: cannot remove ‘/usr/share/manage.py’: No such file or directory
cp: cannot stat ‘../subterfuge/’: No such file or directory
[!] Critical Error! Subterfuge install error could not stat primary path. Trying secondary
...
cp: cannot stat ‘../Subterfuge/’: No such file or directory
[+] Good! Secondary install mechanism succeeded. Installation continuing...
[-] Cleaning up
rm: cannot remove ‘/usr/share/subterfuge/xsubterfuge’: No such file or directory
rm: cannot remove ‘/usr/share/subterfuge/manage.py’: No such file or directory

This seems to be an issue with the new Kali ver 2.0. Subterfuge runs without problems for me on other OS's such as ubuntu, back-box, kali bleeding edge (ver.1.0). 
Please notify me of the fix, need this asap.

**Comment by ghost** [comment]
check that you have django v1.5 installed.  pip install django=="1.5". Subterfuge makes use of django 1.5, and kali comes with a higher version.

**Comment by 0sm0s1z** [comment]
Great catch! I wrote the setup script to work with git clone which creates a Subterfuge/ folder, but downloading as zip and unziping creates a Subterfuge-master folder which is breaking the install script.

I'll modify the setup script to properly handle this and push an update very soon. (for now just rename the folder from Subterfuge-master to Subterfuge. That should fix the problem).

**Comment by kasperfish** [comment]
i can say one thing.... subterfuge sucks.. just use a few other tools to
 accomplish the same result

2015-09-11 0:14 GMT+02:00 Matthew Toussain <notifications@github.com>:

**Comment by giskismet** [comment]
I tried that fix but it didn't work. However I did install subterfuge on my nexus 6 running nethunter 3.0 and noticed it used django 1.7.7 and worked. 

So, pip django==1.7.7 fixed my problem.
