### ISSUE TITLE
subterfuge.settings

### ISSUE THREAD

**Issue by Thor99** [Subterfuge-Framework/Subterfuge#9]
When i run "sudo subterfuge", i get this error: "you have unapplied migrations; your app may not work properly until they are applied. Run 'python manage.py migrate' to apply them."
And when i run "python manage.py migrate", i get this error: "Could not import settings 'subterfuge.settings' (Is it on sys.path? Is there an import error in the settings file?): No module named subterfuge.settings". How can i fix this?

**Comment by 0sm0s1z** [comment]
Don't apply the migration Subterfuge works just fine as is. Ignore the warning message.

**Comment by cool-hack** [comment]
While I click on scan button in UI it gives ImportError for subterfuge.settings.
